name: Build Android App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Install MAUI Workload
      run: dotnet workload install maui
      
    - name: Restore dependencies
      run: dotnet restore StudentApp/StudentApp.csproj
      
    - name: Build Android App
      run: dotnet publish StudentApp/StudentApp.csproj -f net7.0-android -c Release
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: StudentApp-APK
        path: StudentApp/bin/Release/net7.0-android/*-Signed.apk
